### ISSUE TITLE
advertisementWatcher.Received is not unsubscribed

### ISSUE THREAD

**Issue by huybuidac** [microsoft/BluetoothLEExplorer#11]
https://github.com/Microsoft/BluetoothLEExplorer/blob/02e256da6fa607fbd34bd99473733daa5c2a8ec4/BluetoothLEExplorer/BluetoothLEExplorer/Models/GattSampleContext.cs#L460

It should be
```
advertisementWatcher.Received -= AdvertisementWatcher_Received;
```

**Comment by jg4ye** [comment]
@huybuidac Thank you, that fix has been applied.
