### ISSUE TITLE
Sharing some code (using the explorer to control an android device)

### ISSUE THREAD

**Issue by jonathanneels** [microsoft/BluetoothLEExplorer#12]
I've made some alternations to this project so the notifications can be used to control an Android device. 
The receiver is "EIR", my personal A.I.

If you're interested, you can download the project and/or Eir from the following urls:
https://play.google.com/store/apps/details?id=com.fumetsujostudio.eir 
and 
https://play.google.com/store/apps/details?id=com.fumetsujostudio.bleir 

The project (BLEIR) is open-source, so you can find the code here: 
https://drive.google.com/file/d/1mvOPAVF8oJ2-KC2kW36ZzKr2VSd7Eg-h/view?usp=sharing

Enjoy!

**Comment by jg4ye** [comment]
We welcome contributions back to the project.

This does not look like an issue.
