### ISSUE TITLE
Regarding Pre-Pairing

### ISSUE THREAD

**Issue by AadithyaVenkat** [Microsoft/BluetoothLEExplorer#20]
Does this application allow pre-pairing or are there other applications that Microsoft allows pre-pairing and auto connecting of BLE devices

**Comment by AlainMichaud** [comment]
Hi!
Can you clarify what you mean by "pre-pairing" in this case?  Are you referring to the ability to pair/bond a device that is not currently available/connectable?  If that is the case, the answer is no.

However, you can connect to a device without pairing/bonding.

Thanks!

**Comment by AadithyaVenkat** [comment]
What I mean by pre-pairing is that, once the device is visible and it has a certain vendor's name, the application should be able to initiate connection without the user having to navigate through menus and do pairing.

**Comment by AlainMichaud** [comment]
Thanks for the clarification.  So in essence, you'd like the ability to add a watcher that is watching to a particular address or device name that's continuously scanning?

**Comment by AadithyaVenkat** [comment]
So I would have 100s of devices, which are made by a specific vendor(Say JBL headphones) and I would like to connect to them and receive data as and when I am within the range of those devices and once they have some data to send.

**Comment by AlainMichaud** [comment]
Got it.  The Apis this app is using/demonstrating certainly would allow you to build such an app.  You can create an Advertisement watcher with the filtering parameters you need (filtering attribute and RSSI range), then perform the actions you need such as reading/writing or subscribing to a characteristic notification/indication.

**Comment by AadithyaVenkat** [comment]
Ok I did manage to filter the devices using the name these devices have. Assuming each of them would have a common substring, but I have not been able to connect automatically without including the click of the glyph() method.

**Comment by AlainMichaud** [comment]
Perhaps if you share the code of what you've attempted @drache42 can help further.

**Comment by AadithyaVenkat** [comment]
Do I load it in my github and share it ?

**Comment by drache42** [comment]
If you could load on GitHub that would make life easy. I can then take a look.
