### ISSUE TITLE
BLE MLDP Data

### ISSUE THREAD

**Issue by rsocor01** [Microsoft/BluetoothLEExplorer#23]
Hi, is there anyway to receive actual data from the Bluetooth device? All of the data that can be read in this program is only characteristics of the device. Any help is greatly appreciated. Thank you.

**Comment by drache42** [comment]
Characteristics have values, that's what you would read from your peripheral.

**Comment by rsocor01** [comment]
Well, I was hoping to establish a serial communication with the Bluetooth device by using this program.
