### ISSUE TITLE
Removal of DeviceService Page from the Application.

### ISSUE THREAD

**Issue by VinayTShetty** [microsoft/BluetoothLEExplorer#24]
BluetoothLEExplorer application we have 3 XAML Pages.
1)Discover.
2)Device Service Page.
3)Charcterstic Page.
**I need to eliminate the Device Service Page**
**Hardcoding of the UUID,CharctertsticValue is also accepted**.But i need only 2 Pages in this Applicaiton..
1)Discover
3)Charcterstic Page 

After Connection to the Periphereal Device from the Discover xaml,it should navigate directly to Charcterstic xaml
Please guide me on how to achieve this....?

![1](https://user-images.githubusercontent.com/33421892/46570550-7d024680-c983-11e8-8f7b-5d64639b94a5.PNG)
![2_a](https://user-images.githubusercontent.com/33421892/46570551-7d9add00-c983-11e8-9fba-0bb721c147cd.PNG)
![3](https://user-images.githubusercontent.com/33421892/46570552-7d9add00-c983-11e8-8e28-1782be580672.PNG)

**Comment by jg4ye** [comment]
You would have to change the ViewModel for the Discover page to go the hardcoded characteristic page when you click on the device. Then you would need to delete all references of the deviceservices page.
