### ISSUE TITLE
Can only advertise when creating a battery service

### ISSUE THREAD

**Issue by nimazure** [microsoft/BluetoothLEExplorer#31]
When creating a virtual peripheral, there is one toggle switch for advertising the service. However, this switch does not result in enabling advertising. The battery service has three toggle switches. If they are all switched on then the PC starts advertising.

**Comment by jg4ye** [comment]
https://github.com/microsoft/BluetoothLEExplorer/pull/55. Fixed as a side effect of updating with internal version.
