### ISSUE TITLE
Characteristic Page GUI Improvements

### ISSUE THREAD

**Issue by arduino12** [microsoft/BluetoothLEExplorer#35]
**Hi,**

I found the Characteristic Page very hard to work with:
![image](https://user-images.githubusercontent.com/11454280/77969953-b6571080-72f3-11ea-8c10-96828fab0a59.png)

1. I can not select any text with my mouse in order to copy it (the "read value" textbox is disabled).
2. The "write value" textbox is too short! please make it and the "read value" stretch all the way!
3. It will be nice to write the values by pressing Enter key (instead of pressing the "Write" button)

**Thanks for sharing this repo,
Arad**

**Comment by jg4ye** [comment]
Your suggestions are being implemented in this PR: https://github.com/microsoft/BluetoothLEExplorer/pull/52.

Thanks for the feedback.
