### ISSUE TITLE
BluetoothLEExplorer on HoloLens

### ISSUE THREAD

**Issue by gundelsw** [Microsoft/BluetoothLEExplorer#4]
Dear Devs

This app is published on the Windows Store and has an activated ability to work on the HoloLens. When I try to download it there is only a "Get updated" option to install the newest Windows on my HoloLens which obviously is not possible. I also downloaded this git repo and tried to compile it for the HoloLens but I couldn't make it so far. Any suggestions are welcome on how I can use this on a HoloLens.

Cheers
Fredrik

**Comment by drache42** [comment]
Correct, the current version of HoloLens is running an older version of Windows that doesn't have all the required bits yet. Once HoloLens updates Bluetooth LE Explorer should work on it. I don't know if or when HoloLens will update.

**Comment by gundelsw** [comment]
Thank you for your reply - do you know anyone who has knowledge of when BLE will be available on HL?

**Comment by drache42** [comment]
I don't know anyone, sorry.

**Comment by ElliotMebane** [comment]
Fredrik -- I released 2 BLE plugins to the Unity store for HoloLens. Contact me if you'd like a plugin built for your BLE devices: info@roguish.com.

**Comment by FrankGorgenyi** [comment]
HoloLens has announced a [preview for RS4](https://forums.hololens.com/discussion/10192/announcing-the-hololens-rs4-preview ).
