### ISSUE TITLE
BLEExplorer log file

### ISSUE THREAD

**Issue by imranmoezkhan** [microsoft/BluetoothLEExplorer#44]
I've written a very simple ble app on android and BLEExplorer keeps crashing/closing when I try to read any characteristic - even the device name. 
I'm assuming - being a developer tool - the BLEExplorer stores a log/crash dump file somewhere? Also, does it have any settings beyond what is available on the gui - e.g. if I want to request mtu change?

**Comment by imranmoezkhan** [comment]
After trying a number of times and trying to switch notifications on and off again a few times on the phone, BLEExplorer finally threw this error:
![image](https://user-images.githubusercontent.com/34900697/106966386-547bf880-6799-11eb-9cfb-0f7d4a71bfba.png)

Any idea what this might mean?

**Comment by jg4ye** [comment]
It doesn't store a log file, It doesn't have any settings beyond what is available on the gui. If you want to figure out what is going on, the best thing would be to clone this repo, open BluetoothLEExplorer.sln in Visual Studio, and run the app with debugging.

**Comment by jg4ye** [comment]
Also, I can't tell what that exception is because since you don't have the symbols file for this app it doesn't say line numbers/function names.
