### ISSUE TITLE
Advertisment

### ISSUE THREAD

**Issue by hannespreishuber** [Microsoft/BluetoothLEExplorer#5]
I am looking for an app on Windows phone (not kidding) which can receive LE Advertisments. So why not in this app?

**Comment by drache42** [comment]
This app does receive advertisements but that's not the primary purpose. The Microsoft uwp sample apps on GitHub have a le advertisement receiving app which might work better for you.

**Comment by FrankGorgenyi** [comment]
OP using this for APIs support and question seems answered.
