### ISSUE TITLE
Translate new UUID16 GATT Service Characteristics to names

### ISSUE THREAD

**Issue by SamPavezaMS** [microsoft/BluetoothLEExplorer#54]
Recently adopted Service Characteristics should have user friendly names in LE Explorer:
* AICS
* ASCS
* CSIS
* MCS
* MICS
* PACS
* TBS
* VCS
* VOCS

**Comment by jg4ye** [comment]
https://github.com/microsoft/BluetoothLEExplorer/pull/58
